[workspace]
default-members = ["bin/ream"]
members = [
    "bin/ream",
    "crates/common/account_manager",
    "crates/common/api_types/beacon",
    "crates/common/api_types/common",
    "crates/common/api_types/lean",
    "crates/common/chain/beacon",
    "crates/common/chain/lean",
    "crates/common/checkpoint_sync",
    "crates/common/consensus/beacon",
    "crates/common/consensus/lean",
    "crates/common/consensus/misc",
    "crates/common/execution_engine",
    "crates/common/executor",
    "crates/common/fork_choice",
    "crates/common/light_client",
    "crates/common/metrics",
    "crates/common/network_spec",
    "crates/common/node",
    "crates/common/operation_pool",
    "crates/common/polynomial_commitments",
    "crates/common/sync",
    "crates/common/validator/beacon",
    "crates/common/validator/lean",
    "crates/crypto/bls",
    "crates/crypto/keystore",
    "crates/crypto/merkle",
    "crates/crypto/post_quantum",
    "crates/networking/discv5",
    "crates/networking/manager",
    "crates/networking/p2p",
    "crates/networking/syncer",
    "crates/rpc/beacon",
    "crates/rpc/common",
    "crates/rpc/lean",
    "crates/runtime",
    "crates/storage",
    "testing/beacon-api",
    "testing/ef-tests",
    "testing/gossip-validation",
]
resolver = "2"
exclude = ["book/cli"]

[workspace.package]
authors = ["https://github.com/ReamLabs/ream/graphs/contributors"]
edition = "2024"
keywords = [
    "ethereum",
    "beam-chain",
    "blockchain",
    "consensus",
    "protocol",
    "ream",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ReamLabs/ream"
rust-version = "1.88.0"
version = "0.1.0"

[workspace.lints.clippy]
let_and_return = "warn"
uninlined_format_args = "warn"
unnecessary_debug_formatting = "warn"
unwrap_used = "warn"
useless_let_if_seq = "warn"
wildcard_imports = "warn"

[workspace.dependencies]
actix-web = "4.10.2"
actix-web-lab = "0.24.1"
aes = "0.8.4"
alloy-consensus = { version = "1.0", default-features = false }
alloy-primitives = { version = "1.1", features = ['serde'] }
alloy-rlp = { version = "0.3.8", default-features = false, features = ["derive"] }
alloy-rpc-types-beacon = "1.0.8"
alloy-rpc-types-eth = "1.0.7"
anyhow = "1.0"
async-trait = "0.1.86"
bip39 = { version = "2.2.0", features = ["rand"] }
clap = "4"
delay_map = "0.4.1"
directories = { version = "6.0.0" }
discv5 = { version = "0.9.0", features = ["libp2p"] }
enr = "0.13.0"
ethereum_hashing = { git = "https://github.com/ReamLabs/ethereum_hashing.git", rev = "c14a9ad96436e6b8b631faf49a3666e4558b71ae" }
ethereum_serde_utils = "0.8"
ethereum_ssz = "0.9"
ethereum_ssz_derive = "0.9"
eventsource-client = "0.15.0"
futures = "0.3"
hashbrown = "0.15.3"
hashsig = { git = "https://github.com/b-wagn/hash-sig", rev = "287517a763edba7e518b0c1ee5beb868f26f1f66" }
itertools = "0.14"
jsonwebtoken = "9.3.1"
kzg = { git = "https://github.com/grandinetech/rust-kzg" }
lazy_static = "1.5.0"
libp2p = { version = "0.55", default-features = false, features = ["identify", "yamux", "noise", "dns", "serde", "tcp", "tokio", "plaintext", "secp256k1", "macros", "ecdsa", "metrics", "quic", "upnp", "gossipsub", "ping"] }
libp2p-identity = "0.2"
libp2p-mplex = "0.43"
lru = "0.15.0"
parking_lot = "0.12.3"
prometheus_exporter = "0.8.5"
rand = "0.9"
rand_chacha = "0.9"

# ream dependencies
ream-account-manager = { path = "crates/common/account_manager" }
ream-api-types-beacon = { path = "crates/common/api_types/beacon" }
ream-api-types-common = { path = "crates/common/api_types/common" }
ream-api-types-lean = { path = "crates/common/api_types/lean" }
ream-bls = { path = "crates/crypto/bls", features = ["zkcrypto"] } # Default feature is zkcrypto
ream-chain-beacon = { path = "crates/common/chain/beacon" }
ream-chain-lean = { path = "crates/common/chain/lean" }
ream-checkpoint-sync = { path = "crates/common/checkpoint_sync" }
ream-consensus-beacon = { path = "crates/common/consensus/beacon" }
ream-consensus-lean = { path = "crates/common/consensus/lean" }
ream-consensus-misc = { path = "crates/common/consensus/misc" }
ream-discv5 = { path = "crates/networking/discv5" }
ream-execution-engine = { path = "crates/common/execution_engine" }
ream-executor = { path = "crates/common/executor" }
ream-fork-choice = { path = "crates/common/fork_choice" }
ream-keystore = { path = "crates/crypto/keystore" }
ream-light-client = { path = "crates/common/light_client" }
ream-merkle = { path = "crates/crypto/merkle" }
ream-metrics = { path = "crates/common/metrics" }
ream-network-manager = { path = "crates/networking/manager" }
ream-network-spec = { path = "crates/common/network_spec" }
ream-node = { path = "crates/common/node" }
ream-operation-pool = { path = "crates/common/operation_pool" }
ream-p2p = { path = "crates/networking/p2p" }
ream-polynomial-commitments = { path = "crates/common/polynomial_commitments" }
ream-post-quantum-crypto = { path = "crates/crypto/post_quantum" }
ream-rpc-beacon = { path = "crates/rpc/beacon" }
ream-rpc-common = { path = "crates/rpc/common" }
ream-rpc-lean = { path = "crates/rpc/lean" }
ream-storage = { path = "crates/storage" }
ream-sync = { path = "crates/common/sync" }
ream-syncer = { path = "crates/networking/syncer" }
ream-validator-beacon = { path = "crates/common/validator/beacon" }
ream-validator-lean = { path = "crates/common/validator/lean" }
redb = { version = "2.4.0" }
reqwest = { version = "0.12", features = ["json"] }
rstest = "0.25"
rust-kzg-blst = { git = 'https://github.com/grandinetech/rust-kzg.git' }
serde = { version = '1.0', features = ['derive', "rc"] }
serde_json = "1.0.139"
serde_yaml = "0.9"
sha2 = "0.10"
snap = "1.1"
ssz_types = { git = "https://github.com/ReamLabs/ssz_types", branch = "removable-variable-list" }
tempdir = "0.3.7"
tempfile = "3.19"
thiserror = "2.0.11"
tokio = { version = "1.42", features = ["rt", "rt-multi-thread", "sync", "signal", "time", "macros"] }
tokio-util = { version = "0.7", features = ["compat"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-test = "0.2.5"
tree_hash = "0.10"
tree_hash_derive = "0.10"
unicode-normalization = "0.1.24"
url = "2.5"

[patch.crates-io]
ethereum_hashing = { git = "https://github.com/ReamLabs/ethereum_hashing.git" }
quinn-udp = { path = "patch/quinn-udp" }
